admin_wo_locale:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin_dashboard_wo_locale:
    path: /admin/dashboard
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin_dashboard:
    path: /{_locale}/admin/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/admin

sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin

cmf_resource:
    resource: '@CmfResourceRestBundle/Resources/config/routing.yml'
    prefix: /admin

sonata_phpcr_admin_tree:
    resource: '@SonataDoctrinePHPCRAdminBundle/Resources/config/routing/tree.xml'
    prefix: /admin
admin_wo_locale:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin_dashboard_wo_locale:
    path: /admin/dashboard
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin_dashboard:
    path: /{_locale}/admin/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/admin

sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin

cmf_resource:
    resource: '@CmfResourceRestBundle/Resources/config/routing.yml'
    prefix: /admin

sonata_phpcr_admin_tree:
    resource: '@SonataDoctrinePHPCRAdminBundle/Resources/config/routing/tree.xml'
    prefix: /admin

login:
    path: /login
    defaults:
        _controller: 'App\Controller\SecurityController::loginAction'

logout:
    path: /login
    defaults:
        _controller: 'App\Controller\SecurityController::logoutAction'
