<?php

return [
    'Symfony\Bundle\FrameworkBundle\FrameworkBundle' => ['all' => true],
    'Symfony\Bundle\TwigBundle\TwigBundle' => ['all' => true],
    'Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle' => ['all' => true],
    'Doctrine\Bundle\PHPCRBundle\DoctrinePHPCRBundle' => ['all' => true],
    'Doctrine\Bundle\DoctrineBundle\DoctrineBundle' => ['all' => true],
    'Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle' => ['all' => true],
    'App\AppBundle' => ['all' => true],
    'Symfony\Cmf\Bundle\CoreBundle\CmfCoreBundle' => ['all' => true],
    'Knp\Bundle\MenuBundle\KnpMenuBundle' => ['all' => true],
    'Symfony\Cmf\Bundle\MenuBundle\CmfMenuBundle' => ['all' => true],
    'Symfony\Cmf\Bundle\ContentBundle\CmfContentBundle' => ['all' => true],
    'Symfony\Bundle\SecurityBundle\SecurityBundle' => ['all' => true],
    'Symfony\Bundle\MonologBundle\MonologBundle' => ['all' => true],
    'Lunetics\LocaleBundle\LuneticsLocaleBundle' => ['all' => true],
    'JMS\SerializerBundle\JMSSerializerBundle' => ['all' => true],
    'Symfony\Cmf\Bundle\TreeBrowserBundle\CmfTreeBrowserBundle' => ['all' => true],
    'Sonata\DatagridBundle\SonataDatagridBundle' => ['all' => true],
    'Sonata\CoreBundle\SonataCoreBundle' => ['all' => true],
    'Sonata\BlockBundle\SonataBlockBundle' => ['all' => true],
    'Sonata\AdminBundle\SonataAdminBundle' => ['all' => true],
    'Sonata\DoctrinePHPCRAdminBundle\SonataDoctrinePHPCRAdminBundle' => ['all' => true],
    'Symfony\Cmf\Bundle\SonataPhpcrAdminIntegrationBundle\CmfSonataPhpcrAdminIntegrationBundle' => ['all' => true],
    'Symfony\Cmf\Bundle\ResourceBundle\CmfResourceBundle' => ['all' => true],
    'Symfony\Cmf\Bundle\ResourceRestBundle\CmfResourceRestBundle' => ['all' => true],
    'Symfony\Bundle\WebProfilerBundle\WebProfilerBundle' => ['dev' => true, 'test' => true],
];
