index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::indexAction' }
article:
    path: /article/{articleName}
    defaults: { _controller: 'App\Controller\ArticleController::indexAction' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
