home_redirect:
    path: /
    defaults:
        _controller: lunetics_locale.switcher_controller:switchAction
        route: '/cms/routes/%locale%'
        statusCode: 301
        useReferrer: false
article:
    path: /article/{articleName}
    defaults: { _controller: 'App\Controller\ArticleController::indexAction' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
